name: Run Pester Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Run Pester
      shell: pwsh
      run: |
        Import-Module Pester
        Invoke-Pester ./tests/YamCheck.Tests.ps1
        Write-Host 'Total Tests Executed...:  ${{ steps.test_yamcheck.outputs.total_count }}'
        Write-Host 'Total Tests PASSED.....:  ${{ steps.test_yamcheck.outputs.passed_count }}'
        Write-Host 'Total Tests FAILED.....:  ${{ steps.test_yamcheck.outputs.failed_count }}'
